# Generated by Django 3.2.16 on 2025-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250526_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество комментариев'),
        ),
    ]
